// SPDX-License-Identifier: Apache-2.0
// Reflection is restricted to this build-time executable, never the shipped module.
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.Loader;
using System.Text.Json;
using Poima;
using Poima.Build;
if(args.Length==3 && args[0]=="--components")
{
    var path=Path.GetFullPath(args[1]);
    if(new FileInfo(path).Length>64*1024*1024)throw new ArgumentException("Assembly exceeds 64 MiB.");
    var image=File.ReadAllBytes(path);
    File.WriteAllText(Path.GetFullPath(args[2]),ComponentMetadata.Manifest(ComponentMetadata.ReadSchemas(image)));return;
}
if(args.Length!=3)throw new ArgumentException("Expected assembly, fully qualified game type and generated output directory.");
string assemblyPath=Path.GetFullPath(args[0]),output=Path.GetFullPath(args[2]);
if(new FileInfo(assemblyPath).Length>64*1024*1024)throw new ArgumentException("Assembly exceeds 64 MiB.");
var componentSchemas=ComponentMetadata.ReadSchemas(File.ReadAllBytes(assemblyPath));
var resolver=new AssemblyDependencyResolver(assemblyPath);
AssemblyLoadContext.Default.Resolving+=(_,name)=>name.Name==typeof(Game<>).Assembly.GetName().Name?typeof(Game<>).Assembly:resolver.ResolveAssemblyToPath(name) is { } path?AssemblyLoadContext.Default.LoadFromAssemblyPath(path):null;
var assembly=AssemblyLoadContext.Default.LoadFromAssemblyPath(assemblyPath);
var game=assembly.GetType(args[1],true)!;
if(!game.IsPublic || game.IsAbstract || game.IsGenericType || game.GetConstructor(Type.EmptyTypes)==null)throw new ArgumentException("Game must be a public non-generic class with a public parameterless constructor.");
Type? state=null;
for(Type? type=game;type!=null;type=type.BaseType)
{
    if(type.GetFields(BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.DeclaredOnly).Length!=0)throw new ArgumentException("Game classes must be stateless.");
    if(type.IsGenericType && type.GetGenericTypeDefinition()==typeof(Game<>))state=type.GetGenericArguments()[0];
}
if(state==null || !state.IsPublic || state.IsGenericType || !state.IsLayoutSequential)throw new ArgumentException("Expected Game<TState> with public non-generic sequential state.");
string identity=PersistenceMetadata.GameIdentity(game);
bool inertial=typeof(IInertialAnimationGame).IsAssignableFrom(game);
bool masked=typeof(IMaskedAnimationGame).IsAssignableFrom(game);
bool character=typeof(ICharacterInputGame).IsAssignableFrom(game);
bool navigation=typeof(INavigationGame).IsAssignableFrom(game);
string requirements=GameplayRequirements.Json(GameplayRequirements.Features(inertial,masked,character,navigation));
int bytes=Marshal.SizeOf(state);if(bytes is <1 or >65536)throw new ArgumentException("State exceeds 1..65536 bytes.");
var fields=state.GetFields(BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic).OrderBy(f=>f.Name,StringComparer.Ordinal).ToArray();
if(fields.Length is <1 or >128 || fields.Any(f=>!f.IsPublic || f.IsInitOnly || f.Name.Length>64))throw new ArgumentException("Expected 1..128 public mutable state fields.");
var schemaFields=fields.Select(f=> {
    var(kind,size)=f.FieldType==typeof(int)?("int32",4):f.FieldType==typeof(long)?("int64",8):f.FieldType==typeof(float)?("float32",4):f.FieldType==typeof(double)?("float64",8):f.FieldType==typeof(EntityId)?("entity",16):throw new ArgumentException($"Unsupported field {f.Name}.");
    return new {name=f.Name,kind,offset=Marshal.OffsetOf(state,f.Name).ToInt32(),bytes=size};
}).ToArray();
var schema=JsonSerializer.Serialize(new {identity,bytes,fields=schemaFields});
if(componentSchemas is { } components)schema=schema[..^1]+",\"components\":"+components.GetRawText()+"}";
if(PersistenceMetadata.Read(state) is { } persistent)schema=schema[..^1]+",\"persistent\":"+persistent.GetRawText()+"}";
string Name(Type type)=>"global::"+string.Join(".",type.FullName!.Replace('+','.').Split('.').Select(s=>"@"+s));
string assertions=string.Join(" &&\n",schemaFields.Select(f=>$"(byte*)&state.@{f.name}-(byte*)&state=={f.offset}"));
string source=$$"""
// Generated by Poima.NativeGame.Generator. Do not edit.
namespace Poima.NativeGame;
internal static unsafe class Binding
{
    internal const string Schema={{JsonSerializer.Serialize(schema)}};
    internal const string Requirements={{JsonSerializer.Serialize(requirements)}};
    internal static bool RequiresInertial=>{{(inertial ? "true" : "false")}};
    internal static bool RequiresLayers=>{{(masked ? "true" : "false")}};
    internal static bool RequiresCharacterInput=>{{(character ? "true" : "false")}};
    internal static bool RequiresNavigation=>{{(navigation ? "true" : "false")}};
    internal const string TypeName={{JsonSerializer.Serialize(game.FullName)}};
    internal const int StateBytes={{bytes}};
    internal static {{Name(game)}} Create()=>new();
    internal static bool LayoutValid() { {{Name(state)}} state=default;return sizeof({{Name(state)}})==StateBytes && {{assertions}}; }
    internal static void InitializeObject(object game,byte* state)=>(({{Name(game)}})game).Initialize(ref *({{Name(state)}}*)state);
    internal static void ControlObject(object game,byte* state,global::Poima.ControlContext context)=>(({{Name(game)}})game).Control(ref *({{Name(state)}}*)state,context);
    internal static void TickObject(object game,byte* state,global::Poima.GameContext context)=>(({{Name(game)}})game).Tick(ref *({{Name(state)}}*)state,context);
}
""";
Directory.CreateDirectory(output);File.WriteAllText(Path.Combine(output,"Binding.cs"),source);File.WriteAllText(Path.Combine(output,"schema.json"),schema);
File.WriteAllText(Path.Combine(output,"requirements.json"),requirements);
File.WriteAllText(Path.Combine(output,"game-type.txt"),game.FullName);
File.WriteAllText(Path.Combine(output,"game.poima-components.json"),ComponentMetadata.Manifest(componentSchemas));
