# SPDX-License-Identifier: Apache-2.0
set(POIMA_STEAM_AUDIO_ROOT "${CMAKE_SOURCE_DIR}/.cache/sdk/steam-audio-4.8.1/steamaudio" CACHE PATH "Verified Steam Audio 4.8.1 SDK")
if(NOT EXISTS "${POIMA_STEAM_AUDIO_ROOT}/include/phonon.h")
    message(FATAL_ERROR "Steam Audio SDK missing; run python3 scripts/bootstrap_tools.py --only audio.")
endif()
file(READ "${POIMA_STEAM_AUDIO_ROOT}/include/phonon_version.h" poima_audio_version)
if(NOT poima_audio_version MATCHES "STEAMAUDIO_VERSION_MAJOR 4" OR NOT poima_audio_version MATCHES "STEAMAUDIO_VERSION_MINOR 8" OR NOT poima_audio_version MATCHES "STEAMAUDIO_VERSION_PATCH 1")
    message(FATAL_ERROR "This integration is pinned to Steam Audio 4.8.1.")
endif()
add_library(poima_steam_audio SHARED IMPORTED)
if(WIN32)
    set_target_properties(poima_steam_audio PROPERTIES IMPORTED_IMPLIB "${POIMA_STEAM_AUDIO_ROOT}/lib/windows-x64/phonon.lib" IMPORTED_LOCATION "${POIMA_STEAM_AUDIO_ROOT}/lib/windows-x64/phonon.dll")
    install(FILES "${POIMA_STEAM_AUDIO_ROOT}/lib/windows-x64/phonon.dll" DESTINATION bin)
else()
    set_target_properties(poima_steam_audio PROPERTIES IMPORTED_LOCATION "${POIMA_STEAM_AUDIO_ROOT}/lib/linux-x64/libphonon.so")
    install(FILES "${POIMA_STEAM_AUDIO_ROOT}/lib/linux-x64/libphonon.so" DESTINATION lib)
    set(CMAKE_INSTALL_RPATH "$ORIGIN/../lib")
endif()
target_include_directories(poima_core SYSTEM PRIVATE "${POIMA_STEAM_AUDIO_ROOT}/include")
target_link_libraries(poima_core PRIVATE poima_steam_audio)
install(FILES "${POIMA_STEAM_AUDIO_ROOT}/THIRDPARTY.md" "${CMAKE_SOURCE_DIR}/third_party/steam_audio/LICENSE.md" DESTINATION share/poima/licenses/SteamAudio)
